# Generated by Django 4.2.7 on 2023-11-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procsuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
