# Generated by Django 4.2.7 on 2023-12-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_procsuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='procsuser',
            name='isProcsAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
